Added missing comma to default config file
I've generated a new project according to the readme, but the `uiengine.config.js` misses a comma.

```
$ uiengine component button
🚨  creating the component button failed!

Error: Could not read UIengine configuration:

Unexpected identifier
    at Object.read (/.../node_modules/@uiengine/core/lib/configuration.js:63:11)
    at <anonymous>
```